services:
  - type: web
    name: collabboard-backend
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: collabboard-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000

databases:
  - name: collabboard-db
    plan: free
    region: singapore
    databaseName: collabboard
    user: collabboard
